# Generated by Django 4.2.5 on 2023-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_api_app", "0002_alter_comment_id_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Email"),
        ),
    ]
